apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["sleep", "3600"] # Keeps the container running
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80 # Exposes port 80 for nginx
# ssh into pods
# kubectl exec -it multi-container-pod -c curl -- sh
# kubectl exec -it multi-container-pod -c nginx -- sh