apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
  type: NodePort     # Change to clusterIP if needed
# kubectl port-forward svc/nginx-service 5566:80
#
# Access port from curl
# http://<service-name>.<namespace>.svc.cluster.local
# http://nginx-service.default.svc.cluster.local